server:
  port: 8080
  servlet:
    context-path: /be

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: ${DB_PLATFORM:org.hibernate.dialect.H2Dialect}
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha

jwt:
  secret-key: ${JWT_SECRET_KEY:W2B92bmvpFbIhkHavdYaDMq3FoefTugnIiLPFWGpLTLnW3g4ESkaXjBZgmCYuC7S9ZpKuiBs+Pfdf6xyHlLqgg==}
  access-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

security:
  password:
    salt: ${PASSWORD_SALT:my-fixed-secret}
    iterations: ${PASSWORD_ITERATIONS:185000}
    salt-length: ${PASSWORD_SALT_LENGTH:16}

cloud:
  aws:
    s3:
      bucket-name: ${AWS_S3_BUCKET_NAME}